name: Deploy React Application to Server

on:
    push:
        branches:
            - master # Déclenche l'action après un push sur la branche "master"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Étape 1 : Récupérer le code depuis le dépôt
            - name: Checkout code
              uses: actions/checkout@v3

            # Étape 2 : Configurer l'environnement SSH
            - name: Créer le répertoire SSH et ajouter la clé hôte
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
              run: |
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh
                  ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
                  chmod 644 ~/.ssh/known_hosts

            # Étape 3 : Configurer une clé SSH pour se connecter au serveur
            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.DEPLOY_KEY }}

            # Étape 4 : Exécuter le script deploy.sh sur le serveur distant
            -   name: Deploy application
                run: |
                    ssh -o StrictHostKeyChecking=no deployuser@${{ secrets.SERVER_IP }} 'bash /var/www/html/gatcha.fr/waifu-ui/deploy.sh'
